# -*- coding: utf-8 -*-
"""Measure real structure layouts by asking the C compiler.

The problem this solves: a ctypes structure can be internally consistent and
still wrong. `typemap.self_check()` proves the type table agrees with itself; it
cannot prove the table matches what the Windows headers actually define. Only a
compiler can settle that.

So: generate a C file that includes the SDK headers and prints `sizeof` for every
structure and `offsetof` for every field, compile it with MSVC against those same
headers, run it, and commit the result as `tests/data/struct_layout.json`. The
test suite then asserts the ctypes layout against a measurement rather than
against an assumption.

The JSON is checked in deliberately. CI needs no compiler - it asserts against
the committed file. Re-run this only when the target SDK changes, and review the
diff when you do.

Requires MSVC and the Windows SDK. Not needed to run the tests.

Usage:
    python tools/layout_probe.py                 write tests/data/struct_layout.json
    python tools/layout_probe.py --out FILE      write elsewhere
    python tools/layout_probe.py --keep          keep the generated C and exe
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, os.pardir))
sys.path.insert(0, HERE)

import idl  # noqa: E402

DEFAULT_OUT = os.path.join(ROOT, "tests", "data", "struct_layout.json")

#: Only the IDLs this project has actually translated - those are the structures
#: there is anything to compare against.
PROBE_IDLS = [
    "dxgicommon.idl", "dxgitype.idl", "dxgi.idl", "dxgi1_2.idl",
    "d3dcommon.idl", "d3d11.idl", "d3d11sdklayers.idl",
]

#: Headers the probe includes. dxgi1_2.h pulls in dxgi.h, dxgitype.h and
#: dxgicommon.h; d3d11.h pulls in d3dcommon.h.
INCLUDES = ["windows.h", "dxgi1_2.h", "d3d11.h", "d3d11sdklayers.h"]

#: Structures the SDK declares but that are unavailable to a plain C build -
#: guarded by an SDK version macro, or C++ only.
SKIP = {
    "DXGI_ADAPTER_DESC3",       # dxgi1_6
    "DXGI_OUTPUT_DESC1",        # dxgi1_6
}

C_TEMPLATE = """/* Generated by tools/layout_probe.py - do not edit, do not commit.
 * Prints the real sizeof/offsetof for every structure the bindings translate.
 *
 * Output is line-based rather than JSON on purpose: emitting JSON from C means
 * escaping quotes inside printf format strings, which is easy to get subtly
 * wrong. Names travel as %s arguments instead, and Python assembles the JSON.
 *
 *     S <struct> <size>
 *     F <struct> <field> <offset>
 */
#define WIN32_LEAN_AND_MEAN
#define COBJMACROS
#define CINTERFACE
%(includes)s
#include <stdio.h>
#include <stddef.h>

int main(void)
{
%(body)s
    return 0;
}
"""


def find_vcvarsall():
    bases = [
        os.path.join("C:" + os.sep, "Program Files", "Microsoft Visual Studio"),
        os.path.join("C:" + os.sep, "Program Files (x86)", "Microsoft Visual Studio"),
    ]
    found = []
    for base in bases:
        if not os.path.isdir(base):
            continue
        for year in sorted(os.listdir(base)):
            for edition in ("Community", "Professional", "Enterprise", "BuildTools"):
                candidate = os.path.join(base, year, edition, "VC", "Auxiliary",
                                         "Build", "vcvarsall.bat")
                if os.path.isfile(candidate):
                    found.append(candidate)
    return found[-1] if found else None


def collect(sdk):
    """[(struct_name, [field_name, ...] or None)] over the translated IDLs.

    A None field list means the structure contains an anonymous union, so only
    its total size can be measured from the text.
    """
    out, seen = [], set()
    for name in PROBE_IDLS:
        _interfaces, structs = idl.load(sdk, name)
        if structs is None:
            continue
        for struct_name in sorted(structs):
            if struct_name in seen or struct_name in SKIP:
                continue
            seen.add(struct_name)
            spec = structs[struct_name]
            if spec["opaque"]:
                out.append((struct_name, None))
            else:
                out.append((struct_name, [f[1] for f in spec["fields"]]))
    return out


def emit_c(entries):
    """Generate the probe. Struct and field names travel as %s arguments, so no
    quote ever needs escaping inside a format string."""
    lines = []
    for struct_name, fields in entries:
        # NB: single %, not %%. These lines are substituted into C_TEMPLATE as a
        # value, so they are never themselves passed through % formatting.
        lines.append('    printf("S %s %zu\\n", "{n}", sizeof({n}));'
                     .replace("{n}", struct_name))
        for field in (fields or []):
            lines.append(
                '    printf("F %s %s %zu\\n", "{s}", "{f}", offsetof({s}, {f}));'
                .replace("{s}", struct_name).replace("{f}", field))
    return C_TEMPLATE % {
        "includes": "\n".join("#include <%s>" % h for h in INCLUDES),
        "body": "\n".join(lines),
    }


def parse_probe_output(raw):
    """Line-based probe output -> {struct: {'size': int, 'fields': {name: off}}}."""
    out = {}
    for line in raw.splitlines():
        parts = line.split()
        if len(parts) == 3 and parts[0] == "S":
            out.setdefault(parts[1], {"size": 0, "fields": {}})["size"] = int(parts[2])
        elif len(parts) == 4 and parts[0] == "F":
            entry = out.setdefault(parts[1], {"size": 0, "fields": {}})
            entry["fields"][parts[2]] = int(parts[3])
    return out


def compile_and_run(csrc, workdir, keep=False):
    vcvars = find_vcvarsall()
    if not vcvars:
        raise SystemExit("vcvarsall.bat not found - MSVC is required to run the probe.")

    cpath = os.path.join(workdir, "layout_probe.c")
    epath = os.path.join(workdir, "layout_probe.exe")
    with open(cpath, "w", encoding="ascii") as handle:
        handle.write(csrc)

    bat = os.path.join(workdir, "run_probe.bat")
    with open(bat, "w", encoding="ascii") as handle:
        handle.write("@echo off\r\n")
        handle.write('call "%s" x64 >nul\r\n' % vcvars)
        handle.write('cl /nologo /W3 /Fe:"%s" /Fo:"%s\\\\" "%s"\r\n'
                     % (epath, workdir, cpath))
        handle.write("if errorlevel 1 exit /b 1\r\n")
        handle.write('"%s"\r\n' % epath)

    proc = subprocess.run(["cmd", "/c", bat], capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout[-4000:])
        sys.stderr.write(proc.stderr[-4000:])
        raise SystemExit("probe failed to compile or run")

    if not keep:
        for path in (cpath, epath, bat,
                     os.path.join(workdir, "layout_probe.obj")):
            try:
                os.remove(path)
            except OSError:
                pass
    return proc.stdout


def main():
    argv = sys.argv[1:]
    keep = "--keep" in argv
    out_path = DEFAULT_OUT
    if "--out" in argv:
        out_path = os.path.abspath(argv[argv.index("--out") + 1])

    sdk = idl.find_sdk()
    if not sdk:
        raise SystemExit("No Windows SDK found.")
    print("SDK:", sdk)

    entries = collect(sdk)
    measurable = sum(1 for _n, f in entries if f)
    print("structures: %d (%d with field offsets, %d size-only)"
          % (len(entries), measurable, len(entries) - measurable))

    workdir = os.path.join(ROOT, "build", "layout_probe")
    os.makedirs(workdir, exist_ok=True)
    raw = compile_and_run(emit_c(entries), workdir, keep)
    data = parse_probe_output(raw)
    if not data:
        raise SystemExit("probe produced no output")

    payload = {
        "sdk_version": os.path.basename(sdk),
        "pointer_bits": 64,
        "note": ("Generated by tools/layout_probe.py from the SDK headers. "
                 "Committed on purpose so CI needs no compiler. Regenerate only "
                 "when the target SDK changes, and review the diff."),
        "structs": data,
    }
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, indent=1, sort_keys=True)
        handle.write("\n")

    total_fields = sum(len(v["fields"]) for v in data.values())
    print("wrote %s" % out_path)
    print("  %d structures, %d field offsets" % (len(data), total_fields))
    return 0


if __name__ == "__main__":
    sys.exit(main())
